# Generated by Django 5.2.4 on 2025-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreed_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='agreed_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='agreed_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_over_14',
            field=models.BooleanField(default=False),
        ),
    ]
