# Generated by Django 5.2.4 on 2025-07-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_mentorverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorverification',
            old_name='verification_file',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='mentorverification',
            name='intro',
        ),
        migrations.AddField(
            model_name='mentorverification',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
