# Generated by Django 5.2.4 on 2025-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_verification_file_mentorverification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorverification',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
