# Generated by Django 5.2.4 on 2025-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="category",
            field=models.CharField(
                choices=[
                    ("it", "IT/개발"),
                    ("business", "비즈니스"),
                    ("creative", "창의/콘텐츠"),
                    ("career", "커리어/라이프 전환"),
                    ("job", "취업/이직 준비"),
                    ("growth", "자기성장"),
                ],
                default="it",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
