# Generated by Django 5.2.4 on 2025-07-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_obj', to='matching.matchingrequest'),
        ),
    ]
