# Generated by Django 5.2.4 on 2025-07-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_reviewviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrequest',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
